spring.application.name=formbuilder
spring.datasource.url=jdbc:mysql://localhost:3306/formdb
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gemini.api.key=AIzaSyAsIRwnTxc2byZvkzuPiRKtQbRGtqkEym4
spring.servlet.multipart.enabled=true